name: controle.tarefas
description: Projeto para Matéria de APP.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  cupertino_icons: ^0.1.2
  mobx: ^0.4.0
  flutter_mobx: ^0.3.4
  flutter_masked_text: 0.8.0
  bot_toast: ^2.3.1
  provider: 4.0.4
  shared_preferences: 0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.1
  mobx_codegen: ^0.3.11

flutter:
  uses-material-design: true